spring.application.name=finalBack

#Info general DB
spring.datasource.url=jdbc:h2:mem:finalBack_bd
spring.datasource.username=sa
spring.datasource.password=

#Activacion h2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#Activacion JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true